name: Commit message validation

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  commit-message-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Commit message validation
        uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
